#!/bin/bash
install_path=$HOME"/.themes/numix-gtk-theme/"
source_dir="gtk-3.0/assets"
target_dir=$install_path"gtk-3.0/assets/"

cd $source_dir;
for i in *; 
do inkscape $i --export-png=`echo $target_dir$i | sed -e 's/svg$/png/'`; 
echo $target_dir$i;
done

