FROM library/ubuntu:xenial
WORKDIR /opt/oomox-build/

# App and test (xvfb, pylint) deps
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends gtk+3.0 python3-gi xvfb python3-pip psmisc
RUN pip3 install setuptools && \
    pip3 install pylint

# run test
COPY . /opt/oomox-build/
RUN bash -c "\
    set -ueo pipefail ; \
    Xvfb :99 -ac -screen 0 1920x1080x16 -nolisten tcp & \
    echo '== Started Xvfb' ; \
    echo '== Running on system python' ; \
    python3 --version ; \
    export DISPLAY=:99 ; \
    sleep 3 ; \
    \
    pylint oomox_gui ; \
    echo -n plugins/*/oomox_plugin.py | xargs -d ' ' -n 1 pylint ; \
    \
    killall Xvfb"
