FROM base/archlinux
WORKDIR /opt/oomox-build/

# App and test (xvfb, pylint) deps
RUN pacman -Syu --noconfirm && \
    pacman -S --needed --noconfirm gtk3 python-gobject python-pylint xorg-server-xvfb

# run test
COPY . /opt/oomox-build/
RUN bash -c "\
    set -ueo pipefail ; \
    Xvfb :99 -ac -screen 0 1920x1080x16 -nolisten tcp & \
    echo '== Started Xvfb' ; \
    echo '== Running on system python' ; \
    python --version ; \
    export DISPLAY=:99 ; \
    sleep 3 ; \
    \
    pylint oomox_gui ; \
    echo -n plugins/*/oomox_plugin.py | xargs -d ' ' -n 1 pylint ; \
    \
    killall Xvfb"
