class Action: ...
class Component: ...
class Document: ...
class EditableText: ...
class GObjectAccessible: ...
class Hyperlink: ...
class HyperlinkImpl: ...
class Hypertext: ...
class Image: ...
class ImplementorIface: ...
class Misc: ...
class NoOpObject: ...
class NoOpObjectFactory: ...
class Object: ...
class ObjectFactory: ...
class Plug: ...
class Registry: ...
class Relation: ...
class RelationSet: ...
class Selection: ...
class Socket: ...
class StateSet: ...
class StreamableContent: ...
class Table: ...
class TableCell: ...
class Text: ...
class Util: ...
class Value: ...
class Window: ...
class HyperlinkStateFlags: ...
class CoordType: ...
class KeyEventType: ...
class Layer: ...
class RelationType: ...
class Role: ...
class ScrollType: ...
class StateType: ...
class TextAttribute: ...
class TextBoundary: ...
class TextClipType: ...
class TextGranularity: ...
class ValueType: ...
class Attribute: ...
class Implementor: ...
class KeyEventStruct: ...
class PropertyValues: ...
class Range: ...
class Rectangle: ...
class TextRange: ...
class TextRectangle: ...

def attribute_set_free(*args, **kwargs): ...
def focus_tracker_notify(*args, **kwargs): ...
def get_binary_age(*args, **kwargs): ...
def get_default_registry(*args, **kwargs): ...
def get_focus_object(*args, **kwargs): ...
def get_interface_age(*args, **kwargs): ...
def get_major_version(*args, **kwargs): ...
def get_micro_version(*args, **kwargs): ...
def get_minor_version(*args, **kwargs): ...
def get_root(*args, **kwargs): ...
def get_toolkit_name(*args, **kwargs): ...
def get_toolkit_version(*args, **kwargs): ...
def get_version(*args, **kwargs): ...
def relation_type_for_name(*args, **kwargs): ...
def relation_type_get_name(*args, **kwargs): ...
def relation_type_register(*args, **kwargs): ...
def remove_focus_tracker(*args, **kwargs): ...
def remove_global_event_listener(*args, **kwargs): ...
def remove_key_event_listener(*args, **kwargs): ...
def role_for_name(*args, **kwargs): ...
def role_get_localized_name(*args, **kwargs): ...
def role_get_name(*args, **kwargs): ...
def role_register(*args, **kwargs): ...
def state_type_for_name(*args, **kwargs): ...
def state_type_get_name(*args, **kwargs): ...
def state_type_register(*args, **kwargs): ...
def text_attribute_for_name(*args, **kwargs): ...
def text_attribute_get_name(*args, **kwargs): ...
def text_attribute_get_value(*args, **kwargs): ...
def text_attribute_register(*args, **kwargs): ...
def text_free_ranges(*args, **kwargs): ...
def value_type_get_localized_name(*args, **kwargs): ...
def value_type_get_name(*args, **kwargs): ...

BINARY_AGE = ...
INTERFACE_AGE = ...
MAJOR_VERSION = ...
MICRO_VERSION = ...
MINOR_VERSION = ...
VERSION_MIN_REQUIRED = ...
