class Pixbuf: ...
class PixbufAnimation: ...
class PixbufAnimationIter: ...
class PixbufLoader: ...
class PixbufSimpleAnim: ...
class PixbufSimpleAnimIter: ...
class Colorspace: ...
class InterpType: ...
class PixbufAlphaMode: ...
class PixbufError: ...
class PixbufRotation: ...
class PixbufFormat: ...

def pixbuf_error_quark(*args, **kwargs): ...

PIXBUF_FEATURES_H = ...
PIXBUF_MAJOR = ...
PIXBUF_MICRO = ...
PIXBUF_MINOR = ...
PIXBUF_VERSION = ...
