class Action: ...
class ActionGroup: ...
class ActionMap: ...
class AppInfo: ...
class AppInfoMonitor: ...
class AppLaunchContext: ...
class Application: ...
class ApplicationCommandLine: ...
class AsyncInitable: ...
class AsyncResult: ...
class BufferedInputStream: ...
class BufferedOutputStream: ...
class BytesIcon: ...
class Cancellable: ...
class CharsetConverter: ...
class Converter: ...
class ConverterInputStream: ...
class ConverterOutputStream: ...
class Credentials: ...
class DBusActionGroup: ...
class DBusAuthObserver: ...
class DBusConnection: ...
class DBusInterface: ...
class DBusInterfaceSkeleton: ...
class DBusMenuModel: ...
class DBusMessage: ...
class DBusMethodInvocation: ...
class DBusObject: ...
class DBusObjectManager: ...
class DBusObjectManagerClient: ...
class DBusObjectManagerServer: ...
class DBusObjectProxy: ...
class DBusObjectSkeleton: ...
class DBusProxy: ...
class DBusServer: ...
class DataInputStream: ...
class DataOutputStream: ...
class DatagramBased: ...
class DesktopAppInfo: ...
class DesktopAppInfoLookup: ...
class Drive: ...
class DtlsClientConnection: ...
class DtlsConnection: ...
class DtlsServerConnection: ...
class Emblem: ...
class EmblemedIcon: ...
class File: ...
class FileDescriptorBased: ...
class FileEnumerator: ...
class FileIOStream: ...
class FileIcon: ...
class FileInfo: ...
class FileInputStream: ...
class FileMonitor: ...
class FileOutputStream: ...
class FilenameCompleter: ...
class FilterInputStream: ...
class FilterOutputStream: ...
class IOModule: ...
class IOStream: ...
class Icon: ...
class InetAddress: ...
class InetAddressMask: ...
class InetSocketAddress: ...
class Initable: ...
class InputStream: ...
class ListModel: ...
class ListStore: ...
class LoadableIcon: ...
class MemoryInputStream: ...
class MemoryOutputStream: ...
class Menu: ...
class MenuAttributeIter: ...
class MenuItem: ...
class MenuLinkIter: ...
class MenuModel: ...
class Mount: ...
class MountOperation: ...
class NativeVolumeMonitor: ...
class NetworkAddress: ...
class NetworkMonitor: ...
class NetworkService: ...
class Notification: ...
class OutputStream: ...
class Permission: ...
class PollableInputStream: ...
class PollableOutputStream: ...
class PropertyAction: ...
class Proxy: ...
class ProxyAddress: ...
class ProxyAddressEnumerator: ...
class ProxyResolver: ...
class RemoteActionGroup: ...
class Resolver: ...
class Seekable: ...
class Settings: ...
class SettingsBackend: ...
class SimpleAction: ...
class SimpleActionGroup: ...
class SimpleAsyncResult: ...
class SimpleIOStream: ...
class SimplePermission: ...
class SimpleProxyResolver: ...
class Socket: ...
class SocketAddress: ...
class SocketAddressEnumerator: ...
class SocketClient: ...
class SocketConnectable: ...
class SocketConnection: ...
class SocketControlMessage: ...
class SocketListener: ...
class SocketService: ...
class Subprocess: ...
class SubprocessLauncher: ...
class Task: ...
class TcpConnection: ...
class TcpWrapperConnection: ...
class TestDBus: ...
class ThemedIcon: ...
class ThreadedSocketService: ...
class TlsBackend: ...
class TlsCertificate: ...
class TlsClientConnection: ...
class TlsConnection: ...
class TlsDatabase: ...
class TlsFileDatabase: ...
class TlsInteraction: ...
class TlsPassword: ...
class TlsServerConnection: ...
class UnixConnection: ...
class UnixCredentialsMessage: ...
class UnixFDList: ...
class UnixFDMessage: ...
class UnixInputStream: ...
class UnixMountMonitor: ...
class UnixOutputStream: ...
class UnixSocketAddress: ...
class Vfs: ...
class Volume: ...
class VolumeMonitor: ...
class ZlibCompressor: ...
class ZlibDecompressor: ...
class AppInfoCreateFlags: ...
class ApplicationFlags: ...
class AskPasswordFlags: ...
class BusNameOwnerFlags: ...
class BusNameWatcherFlags: ...
class ConverterFlags: ...
class DBusCallFlags: ...
class DBusCapabilityFlags: ...
class DBusConnectionFlags: ...
class DBusInterfaceSkeletonFlags: ...
class DBusMessageFlags: ...
class DBusObjectManagerClientFlags: ...
class DBusPropertyInfoFlags: ...
class DBusProxyFlags: ...
class DBusSendMessageFlags: ...
class DBusServerFlags: ...
class DBusSignalFlags: ...
class DBusSubtreeFlags: ...
class DriveStartFlags: ...
class FileAttributeInfoFlags: ...
class FileCopyFlags: ...
class FileCreateFlags: ...
class FileMeasureFlags: ...
class FileMonitorFlags: ...
class FileQueryInfoFlags: ...
class IOStreamSpliceFlags: ...
class MountMountFlags: ...
class MountUnmountFlags: ...
class OutputStreamSpliceFlags: ...
class ResourceFlags: ...
class ResourceLookupFlags: ...
class SettingsBindFlags: ...
class SocketMsgFlags: ...
class SubprocessFlags: ...
class TestDBusFlags: ...
class TlsCertificateFlags: ...
class TlsDatabaseVerifyFlags: ...
class TlsPasswordFlags: ...
class BusType: ...
class ConverterResult: ...
class CredentialsType: ...
class DBusError: ...
class DBusMessageByteOrder: ...
class DBusMessageHeaderField: ...
class DBusMessageType: ...
class DataStreamByteOrder: ...
class DataStreamNewlineType: ...
class DriveStartStopType: ...
class EmblemOrigin: ...
class FileAttributeStatus: ...
class FileAttributeType: ...
class FileMonitorEvent: ...
class FileType: ...
class FilesystemPreviewType: ...
class IOErrorEnum: ...
class IOModuleScopeFlags: ...
class MountOperationResult: ...
class NetworkConnectivity: ...
class NotificationPriority: ...
class PasswordSave: ...
class ResolverError: ...
class ResolverRecordType: ...
class ResourceError: ...
class SocketClientEvent: ...
class SocketFamily: ...
class SocketListenerEvent: ...
class SocketProtocol: ...
class SocketType: ...
class TlsAuthenticationMode: ...
class TlsCertificateRequestFlags: ...
class TlsDatabaseLookupFlags: ...
class TlsError: ...
class TlsInteractionResult: ...
class TlsRehandshakeMode: ...
class UnixSocketAddressType: ...
class ZlibCompressorFormat: ...
class ActionEntry: ...
class DBusAnnotationInfo: ...
class DBusArgInfo: ...
class DBusErrorEntry: ...
class DBusInterfaceInfo: ...
class DBusInterfaceVTable: ...
class DBusMethodInfo: ...
class DBusNodeInfo: ...
class DBusPropertyInfo: ...
class DBusSignalInfo: ...
class DBusSubtreeVTable: ...
class FileAttributeInfo: ...
class FileAttributeInfoList: ...
class FileAttributeMatcher: ...
class IOExtension: ...
class IOExtensionPoint: ...
class IOModuleScope: ...
class IOSchedulerJob: ...
class InputMessage: ...
class InputVector: ...
class NativeSocketAddress: ...
class OutputMessage: ...
class OutputVector: ...
class Resource: ...
class SettingsSchema: ...
class SettingsSchemaKey: ...
class SettingsSchemaSource: ...
class SrvTarget: ...
class StaticResource: ...
class UnixMountEntry: ...
class UnixMountPoint: ...

def action_name_is_valid(*args, **kwargs): ...
def action_parse_detailed_name(*args, **kwargs): ...
def action_print_detailed_name(*args, **kwargs): ...
def app_info_create_from_commandline(*args, **kwargs): ...
def app_info_get_all(*args, **kwargs): ...
def app_info_get_all_for_type(*args, **kwargs): ...
def app_info_get_default_for_type(*args, **kwargs): ...
def app_info_get_default_for_uri_scheme(*args, **kwargs): ...
def app_info_get_fallback_for_type(*args, **kwargs): ...
def app_info_get_recommended_for_type(*args, **kwargs): ...
def app_info_launch_default_for_uri(*args, **kwargs): ...
def app_info_launch_default_for_uri_async(*args, **kwargs): ...
def app_info_launch_default_for_uri_finish(*args, **kwargs): ...
def app_info_reset_type_associations(*args, **kwargs): ...
def async_initable_newv_async(*args, **kwargs): ...
def bus_get(*args, **kwargs): ...
def bus_get_finish(*args, **kwargs): ...
def bus_get_sync(*args, **kwargs): ...
def bus_own_name(*args, **kwargs): ...
def bus_own_name_on_connection(*args, **kwargs): ...
def bus_unown_name(*args, **kwargs): ...
def bus_unwatch_name(*args, **kwargs): ...
def bus_watch_name(*args, **kwargs): ...
def bus_watch_name_on_connection(*args, **kwargs): ...
def content_type_can_be_executable(*args, **kwargs): ...
def content_type_equals(*args, **kwargs): ...
def content_type_from_mime_type(*args, **kwargs): ...
def content_type_get_description(*args, **kwargs): ...
def content_type_get_generic_icon_name(*args, **kwargs): ...
def content_type_get_icon(*args, **kwargs): ...
def content_type_get_mime_type(*args, **kwargs): ...
def content_type_get_symbolic_icon(*args, **kwargs): ...
def content_type_guess(*args, **kwargs): ...
def content_type_guess_for_tree(*args, **kwargs): ...
def content_type_is_a(*args, **kwargs): ...
def content_type_is_mime_type(*args, **kwargs): ...
def content_type_is_unknown(*args, **kwargs): ...
def content_types_get_registered(*args, **kwargs): ...
def dbus_address_escape_value(*args, **kwargs): ...
def dbus_address_get_for_bus_sync(*args, **kwargs): ...
def dbus_address_get_stream(*args, **kwargs): ...
def dbus_address_get_stream_finish(*args, **kwargs): ...
def dbus_address_get_stream_sync(*args, **kwargs): ...
def dbus_annotation_info_lookup(*args, **kwargs): ...
def dbus_error_encode_gerror(*args, **kwargs): ...
def dbus_error_get_remote_error(*args, **kwargs): ...
def dbus_error_is_remote_error(*args, **kwargs): ...
def dbus_error_new_for_dbus_error(*args, **kwargs): ...
def dbus_error_quark(*args, **kwargs): ...
def dbus_error_register_error(*args, **kwargs): ...
def dbus_error_register_error_domain(*args, **kwargs): ...
def dbus_error_strip_remote_error(*args, **kwargs): ...
def dbus_error_unregister_error(*args, **kwargs): ...
def dbus_generate_guid(*args, **kwargs): ...
def dbus_gvalue_to_gvariant(*args, **kwargs): ...
def dbus_gvariant_to_gvalue(*args, **kwargs): ...
def dbus_is_address(*args, **kwargs): ...
def dbus_is_guid(*args, **kwargs): ...
def dbus_is_interface_name(*args, **kwargs): ...
def dbus_is_member_name(*args, **kwargs): ...
def dbus_is_name(*args, **kwargs): ...
def dbus_is_supported_address(*args, **kwargs): ...
def dbus_is_unique_name(*args, **kwargs): ...
def dtls_client_connection_new(*args, **kwargs): ...
def dtls_server_connection_new(*args, **kwargs): ...
def file_new_for_commandline_arg(*args, **kwargs): ...
def file_new_for_commandline_arg_and_cwd(*args, **kwargs): ...
def file_new_for_path(*args, **kwargs): ...
def file_new_for_uri(*args, **kwargs): ...
def file_new_tmp(*args, **kwargs): ...
def file_parse_name(*args, **kwargs): ...
def icon_deserialize(*args, **kwargs): ...
def icon_hash(*args, **kwargs): ...
def icon_new_for_string(*args, **kwargs): ...
def initable_newv(*args, **kwargs): ...
def io_error_from_errno(*args, **kwargs): ...
def io_error_quark(*args, **kwargs): ...
def io_extension_point_implement(*args, **kwargs): ...
def io_extension_point_lookup(*args, **kwargs): ...
def io_extension_point_register(*args, **kwargs): ...
def io_modules_load_all_in_directory(*args, **kwargs): ...
def io_modules_load_all_in_directory_with_scope(*args, **kwargs): ...
def io_modules_scan_all_in_directory(*args, **kwargs): ...
def io_modules_scan_all_in_directory_with_scope(*args, **kwargs): ...
def io_scheduler_cancel_all_jobs(*args, **kwargs): ...
def io_scheduler_push_job(*args, **kwargs): ...
def keyfile_settings_backend_new(*args, **kwargs): ...
def memory_settings_backend_new(*args, **kwargs): ...
def network_monitor_get_default(*args, **kwargs): ...
def networking_init(*args, **kwargs): ...
def null_settings_backend_new(*args, **kwargs): ...
def pollable_source_new(*args, **kwargs): ...
def pollable_source_new_full(*args, **kwargs): ...
def pollable_stream_read(*args, **kwargs): ...
def pollable_stream_write(*args, **kwargs): ...
def pollable_stream_write_all(*args, **kwargs): ...
def proxy_get_default_for_protocol(*args, **kwargs): ...
def proxy_resolver_get_default(*args, **kwargs): ...
def resolver_error_quark(*args, **kwargs): ...
def resource_error_quark(*args, **kwargs): ...
def resource_load(*args, **kwargs): ...
def resources_enumerate_children(*args, **kwargs): ...
def resources_get_info(*args, **kwargs): ...
def resources_lookup_data(*args, **kwargs): ...
def resources_open_stream(*args, **kwargs): ...
def resources_register(*args, **kwargs): ...
def resources_unregister(*args, **kwargs): ...
def settings_schema_source_get_default(*args, **kwargs): ...
def simple_async_report_gerror_in_idle(*args, **kwargs): ...
def tls_backend_get_default(*args, **kwargs): ...
def tls_client_connection_new(*args, **kwargs): ...
def tls_error_quark(*args, **kwargs): ...
def tls_file_database_new(*args, **kwargs): ...
def tls_server_connection_new(*args, **kwargs): ...
def unix_is_mount_path_system_internal(*args, **kwargs): ...
def unix_is_system_device_path(*args, **kwargs): ...
def unix_is_system_fs_type(*args, **kwargs): ...
def unix_mount_at(*args, **kwargs): ...
def unix_mount_compare(*args, **kwargs): ...
def unix_mount_copy(*args, **kwargs): ...
def unix_mount_for(*args, **kwargs): ...
def unix_mount_free(*args, **kwargs): ...
def unix_mount_get_device_path(*args, **kwargs): ...
def unix_mount_get_fs_type(*args, **kwargs): ...
def unix_mount_get_mount_path(*args, **kwargs): ...
def unix_mount_get_options(*args, **kwargs): ...
def unix_mount_guess_can_eject(*args, **kwargs): ...
def unix_mount_guess_icon(*args, **kwargs): ...
def unix_mount_guess_name(*args, **kwargs): ...
def unix_mount_guess_should_display(*args, **kwargs): ...
def unix_mount_guess_symbolic_icon(*args, **kwargs): ...
def unix_mount_is_readonly(*args, **kwargs): ...
def unix_mount_is_system_internal(*args, **kwargs): ...
def unix_mount_points_changed_since(*args, **kwargs): ...
def unix_mount_points_get(*args, **kwargs): ...
def unix_mounts_changed_since(*args, **kwargs): ...
def unix_mounts_get(*args, **kwargs): ...

DESKTOP_APP_INFO_LOOKUP_EXTENSION_POINT_NAME = ...
DRIVE_IDENTIFIER_KIND_UNIX_DEVICE = ...
FILE_ATTRIBUTE_ACCESS_CAN_DELETE = ...
FILE_ATTRIBUTE_ACCESS_CAN_EXECUTE = ...
FILE_ATTRIBUTE_ACCESS_CAN_READ = ...
FILE_ATTRIBUTE_ACCESS_CAN_RENAME = ...
FILE_ATTRIBUTE_ACCESS_CAN_TRASH = ...
FILE_ATTRIBUTE_ACCESS_CAN_WRITE = ...
FILE_ATTRIBUTE_DOS_IS_ARCHIVE = ...
FILE_ATTRIBUTE_DOS_IS_SYSTEM = ...
FILE_ATTRIBUTE_ETAG_VALUE = ...
FILE_ATTRIBUTE_FILESYSTEM_FREE = ...
FILE_ATTRIBUTE_FILESYSTEM_READONLY = ...
FILE_ATTRIBUTE_FILESYSTEM_REMOTE = ...
FILE_ATTRIBUTE_FILESYSTEM_SIZE = ...
FILE_ATTRIBUTE_FILESYSTEM_TYPE = ...
FILE_ATTRIBUTE_FILESYSTEM_USED = ...
FILE_ATTRIBUTE_FILESYSTEM_USE_PREVIEW = ...
FILE_ATTRIBUTE_GVFS_BACKEND = ...
FILE_ATTRIBUTE_ID_FILE = ...
FILE_ATTRIBUTE_ID_FILESYSTEM = ...
FILE_ATTRIBUTE_MOUNTABLE_CAN_EJECT = ...
FILE_ATTRIBUTE_MOUNTABLE_CAN_MOUNT = ...
FILE_ATTRIBUTE_MOUNTABLE_CAN_POLL = ...
FILE_ATTRIBUTE_MOUNTABLE_CAN_START = ...
FILE_ATTRIBUTE_MOUNTABLE_CAN_START_DEGRADED = ...
FILE_ATTRIBUTE_MOUNTABLE_CAN_STOP = ...
FILE_ATTRIBUTE_MOUNTABLE_CAN_UNMOUNT = ...
FILE_ATTRIBUTE_MOUNTABLE_HAL_UDI = ...
FILE_ATTRIBUTE_MOUNTABLE_IS_MEDIA_CHECK_AUTOMATIC = ...
FILE_ATTRIBUTE_MOUNTABLE_START_STOP_TYPE = ...
FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE = ...
FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE_FILE = ...
FILE_ATTRIBUTE_OWNER_GROUP = ...
FILE_ATTRIBUTE_OWNER_USER = ...
FILE_ATTRIBUTE_OWNER_USER_REAL = ...
FILE_ATTRIBUTE_PREVIEW_ICON = ...
FILE_ATTRIBUTE_RECENT_MODIFIED = ...
FILE_ATTRIBUTE_SELINUX_CONTEXT = ...
FILE_ATTRIBUTE_STANDARD_ALLOCATED_SIZE = ...
FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE = ...
FILE_ATTRIBUTE_STANDARD_COPY_NAME = ...
FILE_ATTRIBUTE_STANDARD_DESCRIPTION = ...
FILE_ATTRIBUTE_STANDARD_DISPLAY_NAME = ...
FILE_ATTRIBUTE_STANDARD_EDIT_NAME = ...
FILE_ATTRIBUTE_STANDARD_FAST_CONTENT_TYPE = ...
FILE_ATTRIBUTE_STANDARD_ICON = ...
FILE_ATTRIBUTE_STANDARD_IS_BACKUP = ...
FILE_ATTRIBUTE_STANDARD_IS_HIDDEN = ...
FILE_ATTRIBUTE_STANDARD_IS_SYMLINK = ...
FILE_ATTRIBUTE_STANDARD_IS_VIRTUAL = ...
FILE_ATTRIBUTE_STANDARD_IS_VOLATILE = ...
FILE_ATTRIBUTE_STANDARD_NAME = ...
FILE_ATTRIBUTE_STANDARD_SIZE = ...
FILE_ATTRIBUTE_STANDARD_SORT_ORDER = ...
FILE_ATTRIBUTE_STANDARD_SYMBOLIC_ICON = ...
FILE_ATTRIBUTE_STANDARD_SYMLINK_TARGET = ...
FILE_ATTRIBUTE_STANDARD_TARGET_URI = ...
FILE_ATTRIBUTE_STANDARD_TYPE = ...
FILE_ATTRIBUTE_THUMBNAILING_FAILED = ...
FILE_ATTRIBUTE_THUMBNAIL_IS_VALID = ...
FILE_ATTRIBUTE_THUMBNAIL_PATH = ...
FILE_ATTRIBUTE_TIME_ACCESS = ...
FILE_ATTRIBUTE_TIME_ACCESS_USEC = ...
FILE_ATTRIBUTE_TIME_CHANGED = ...
FILE_ATTRIBUTE_TIME_CHANGED_USEC = ...
FILE_ATTRIBUTE_TIME_CREATED = ...
FILE_ATTRIBUTE_TIME_CREATED_USEC = ...
FILE_ATTRIBUTE_TIME_MODIFIED = ...
FILE_ATTRIBUTE_TIME_MODIFIED_USEC = ...
FILE_ATTRIBUTE_TRASH_DELETION_DATE = ...
FILE_ATTRIBUTE_TRASH_ITEM_COUNT = ...
FILE_ATTRIBUTE_TRASH_ORIG_PATH = ...
FILE_ATTRIBUTE_UNIX_BLOCKS = ...
FILE_ATTRIBUTE_UNIX_BLOCK_SIZE = ...
FILE_ATTRIBUTE_UNIX_DEVICE = ...
FILE_ATTRIBUTE_UNIX_GID = ...
FILE_ATTRIBUTE_UNIX_INODE = ...
FILE_ATTRIBUTE_UNIX_IS_MOUNTPOINT = ...
FILE_ATTRIBUTE_UNIX_MODE = ...
FILE_ATTRIBUTE_UNIX_NLINK = ...
FILE_ATTRIBUTE_UNIX_RDEV = ...
FILE_ATTRIBUTE_UNIX_UID = ...
MENU_ATTRIBUTE_ACTION = ...
MENU_ATTRIBUTE_ACTION_NAMESPACE = ...
MENU_ATTRIBUTE_ICON = ...
MENU_ATTRIBUTE_LABEL = ...
MENU_ATTRIBUTE_TARGET = ...
MENU_LINK_SECTION = ...
MENU_LINK_SUBMENU = ...
NATIVE_VOLUME_MONITOR_EXTENSION_POINT_NAME = ...
NETWORK_MONITOR_EXTENSION_POINT_NAME = ...
PROXY_EXTENSION_POINT_NAME = ...
PROXY_RESOLVER_EXTENSION_POINT_NAME = ...
SETTINGS_BACKEND_EXTENSION_POINT_NAME = ...
TLS_BACKEND_EXTENSION_POINT_NAME = ...
TLS_DATABASE_PURPOSE_AUTHENTICATE_CLIENT = ...
TLS_DATABASE_PURPOSE_AUTHENTICATE_SERVER = ...
VFS_EXTENSION_POINT_NAME = ...
VOLUME_IDENTIFIER_KIND_CLASS = ...
VOLUME_IDENTIFIER_KIND_HAL_UDI = ...
VOLUME_IDENTIFIER_KIND_LABEL = ...
VOLUME_IDENTIFIER_KIND_NFS_MOUNT = ...
VOLUME_IDENTIFIER_KIND_UNIX_DEVICE = ...
VOLUME_IDENTIFIER_KIND_UUID = ...
VOLUME_MONITOR_EXTENSION_POINT_NAME = ...
