class Context: ...
class Engine: ...
class EngineLang: ...
class EngineShape: ...
class Font: ...
class FontFace: ...
class FontFamily: ...
class FontMap: ...
class Fontset: ...
class FontsetSimple: ...
class Layout: ...
class Renderer: ...
class FontMask: ...
class Alignment: ...
class AttrType: ...
class BidiType: ...
class CoverageLevel: ...
class Direction: ...
class EllipsizeMode: ...
class Gravity: ...
class GravityHint: ...
class RenderPart: ...
class Script: ...
class Stretch: ...
class Style: ...
class TabAlign: ...
class Underline: ...
class Variant: ...
class Weight: ...
class WrapMode: ...
class Analysis: ...
class AttrClass: ...
class AttrColor: ...
class AttrFloat: ...
class AttrFontDesc: ...
class AttrFontFeatures: ...
class AttrInt: ...
class AttrIterator: ...
class AttrLanguage: ...
class AttrList: ...
class AttrShape: ...
class AttrSize: ...
class AttrString: ...
class Attribute: ...
class Color: ...
class Coverage: ...
class EngineInfo: ...
class EngineScriptInfo: ...
class FontDescription: ...
class FontMetrics: ...
class GlyphGeometry: ...
class GlyphInfo: ...
class GlyphItem: ...
class GlyphItemIter: ...
class GlyphString: ...
class GlyphVisAttr: ...
class IncludedModule: ...
class Item: ...
class Language: ...
class LayoutIter: ...
class LayoutLine: ...
class LogAttr: ...
class Map: ...
class Matrix: ...
class Rectangle: ...
class ScriptIter: ...
class TabArray: ...

def attr_type_get_name(*args, **kwargs): ...
def attr_type_register(*args, **kwargs): ...
def bidi_type_for_unichar(*args, **kwargs): ...
def break_(*args, **kwargs): ...
def config_key_get(*args, **kwargs): ...
def config_key_get_system(*args, **kwargs): ...
def default_break(*args, **kwargs): ...
def extents_to_pixels(*args, **kwargs): ...
def find_base_dir(*args, **kwargs): ...
def find_paragraph_boundary(*args, **kwargs): ...
def font_description_from_string(*args, **kwargs): ...
def get_lib_subdirectory(*args, **kwargs): ...
def get_log_attrs(*args, **kwargs): ...
def get_mirror_char(*args, **kwargs): ...
def get_sysconf_subdirectory(*args, **kwargs): ...
def gravity_get_for_matrix(*args, **kwargs): ...
def gravity_get_for_script(*args, **kwargs): ...
def gravity_get_for_script_and_width(*args, **kwargs): ...
def gravity_to_rotation(*args, **kwargs): ...
def is_zero_width(*args, **kwargs): ...
def itemize(*args, **kwargs): ...
def itemize_with_base_dir(*args, **kwargs): ...
def language_from_string(*args, **kwargs): ...
def language_get_default(*args, **kwargs): ...
def log2vis_get_embedding_levels(*args, **kwargs): ...
def lookup_aliases(*args, **kwargs): ...
def markup_parser_finish(*args, **kwargs): ...
def markup_parser_new(*args, **kwargs): ...
def module_register(*args, **kwargs): ...
def parse_enum(*args, **kwargs): ...
def parse_markup(*args, **kwargs): ...
def parse_stretch(*args, **kwargs): ...
def parse_style(*args, **kwargs): ...
def parse_variant(*args, **kwargs): ...
def parse_weight(*args, **kwargs): ...
def quantize_line_geometry(*args, **kwargs): ...
def read_line(*args, **kwargs): ...
def reorder_items(*args, **kwargs): ...
def scan_int(*args, **kwargs): ...
def scan_string(*args, **kwargs): ...
def scan_word(*args, **kwargs): ...
def script_for_unichar(*args, **kwargs): ...
def script_get_sample_language(*args, **kwargs): ...
def shape(*args, **kwargs): ...
def shape_full(*args, **kwargs): ...
def skip_space(*args, **kwargs): ...
def split_file_list(*args, **kwargs): ...
def trim_string(*args, **kwargs): ...
def unichar_direction(*args, **kwargs): ...
def units_from_double(*args, **kwargs): ...
def units_to_double(*args, **kwargs): ...
def version(*args, **kwargs): ...
def version_check(*args, **kwargs): ...
def version_string(*args, **kwargs): ...

ANALYSIS_FLAG_CENTERED_BASELINE = ...
ANALYSIS_FLAG_IS_ELLIPSIS = ...
ATTR_INDEX_FROM_TEXT_BEGINNING = ...
ENGINE_TYPE_LANG = ...
ENGINE_TYPE_SHAPE = ...
GLYPH_EMPTY = ...
GLYPH_INVALID_INPUT = ...
GLYPH_UNKNOWN_FLAG = ...
RENDER_TYPE_NONE = ...
SCALE = ...
UNKNOWN_GLYPH_HEIGHT = ...
UNKNOWN_GLYPH_WIDTH = ...
VERSION_MIN_REQUIRED = ...
