# from . import alg as alg, haillow as haillow
from _typeshed import Incomplete

class Haishoku:
    def __init__(self) -> None: ...
    # @classmethod
    # def loadHaishoku(self, image_path): ...
    # @property
    # def dominant(self): ...
    # @property
    # def palette(self): ...
    # def getColorsMean(image_path): ...
    # def showPalette(image_path) -> None: ...
    # def showDominant(image_path) -> None: ...
    # def getDominant(image_path: Incomplete | None = ...): ...
    @classmethod
    def getPalette(cls, image_path: str) -> list[tuple[float, tuple[int, int, int]]]:
        ...
