FROM base/archlinux
WORKDIR /opt/oomox-build/

# App and test (xvfb, pylint) deps
RUN pacman -Syu --noconfirm && \
    pacman -S --needed --noconfirm gtk3 python-gobject python-pylint xorg-server-xvfb

# run test
COPY . /opt/oomox-build/
RUN bash ./maintenance_scripts/run_ci.sh
