FROM library/ubuntu:xenial
WORKDIR /opt/oomox-build/

# App and test (xvfb, pylint) deps
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends gtk+3.0 python3-gi xvfb python3-pip psmisc
RUN pip3 install setuptools && \
    pip3 install pylint

# run test
COPY . /opt/oomox-build/
RUN bash ./maintenance_scripts/run_test.sh
