# pylint: disable=multiple-statements,missing-docstring,too-few-public-methods,pointless-statement

class GLib: ...


class Gdk: ...


class GdkPixbuf: ...


class Pango: ...


class Gio: ...


class Gtk:
    class Box: ...
    class Button: ...
    class Dialog: ...
    class Grid: ...
    class HeaderBar: ...
    class Image: ...
    class Label: ...
    class ListBox: ...
    class MenuButton: ...
    class Widget: ...

# vim: ft=python
