#!/bin/sh

set -e

case "$1" in

  configure)
    if [ -x /usr/bin/desktop-file-install ]; then
        desktop-file-install /usr/share/applications/com.github.themix_project.Oomox.desktop > /dev/null 2>&1
    fi
    python3 -O -m compileall /opt/oomox/oomox_gui
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac



exit 0
